[project]
name = "diagrams"
version = "0.0.0"
requires-python = ">=3.8,<3.11"
dependencies = ["drawsvg~=2.0", "sympy"]

[tool.pdm.dev-dependencies]
dev = ["watchfiles"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
