[project]
name = "diagrams"
version = "0.0.0"
requires-python = ">=3.10,<3.11"
dependencies = ["drawsvg", "networkx", "numpy", "sympy", "watchfiles"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
