name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - run: pdm install
      - run: pdm run diagram.py -m flower -f draw -o out/flower.svg
      - uses: actions/upload-artifact@v3
        with:
          name: diagrams
          path: out
